---
  - name: installing apache2
    package:
      name: apache2
      state: latest

  - name: add php repo
    apt_repository: repo='ppa:ondrej/php'

  - name: install php
    package:
      name=php5 state=latest

  - name: installing php packages
    package: 
      name: "{{ item }}" 
      state: latest 
      update_cache: yes
    with_items:
        - php5-cli
        - php5-curl
        - php5-fpm
        - php5-mcrypt
        - php5-mysql
        - php5-sqlite
        - php5-intl
    notify:
      - restart apache
      - restart php5-fpm
