---
  - name: delete default index.html from apache
    file:
      name: /var/www/html/index.html
      state: absent

  - name: adding application to apache
    copy:
      src: "{{ role_path }}/files/"
      dest: /var/www/html

  - name: making app files accesable
    file:
      path: /var/www/html
      recurse: yes
      mode: '0555'
    notify:
      - restart apache
      - restart php5-fpm
